# Generated by Django 4.2.1 on 2023-08-17 06:10

from django.db import migrations, models
import main.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ism Familya')),
                ('username', models.CharField(max_length=50, verbose_name='Foydalanuvchi nomi')),
                ('user_id', models.PositiveBigIntegerField(unique=True, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Bot foydalanuvchisi',
                'verbose_name_plural': 'Bot foydalanuvchilari',
            },
        ),
        migrations.CreateModel(
            name='HumanInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, validators=[main.validator.phone_validator], verbose_name='Telefon raqam')),
            ],
            options={
                'verbose_name': 'Kursga yozilganlar',
                'verbose_name_plural': 'Kursga yozilganlar',
                'db_table': 'main_humaninfo',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ForexSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'signal',
                'verbose_name_plural': 'signal',
            },
        ),
    ]
