# Generated by Django 4.2.1 on 2023-08-17 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forexsignal',
            options={'verbose_name': 'forex signal', 'verbose_name_plural': 'forex signals'},
        ),
    ]
