# Generated by Django 4.2.1 on 2023-08-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_forexsignal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forexsignal',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]

